version: "3.9"
    
services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 0.0.0.0:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: aa111111
      MYSQL_DATABASE: store
      MYSQL_USER: admin
      MYSQL_PASSWORD: aa111111

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
      
  # redis:
  #   image: docker.io/bitnami/redis
  #   command: '/opt/bitnami/scripts/redis/run.sh --maxmemory 100mb'
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     # - REDIS_PASSWORD=aa111111
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - 'redis_data:/bitnami/redis/data'

  redis-alpine:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    # volumes:
      # - redis-data:/var/lib/redis
    #   - redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  db_data: {}
  # redis_data:
  #   driver: local